### ISSUE TITLE
Install to `/usr/local/`, not `/usr/`

### ISSUE THREAD

**Issue by Aman9das** [omegaui/app_fleet#20]
The app is not managed by the host package manager. It should thus be installed to `/usr/local/` and not `/usr/`.

Also doesn't run on Silverblue and other immutable distriutions as a result.

refs: https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard#Directory_structure

**Comment by omegaui** [comment]
Hello @Aman9das 
Thank you for taking your time and contributing to App Fleet.

> Also doesn't run on Silverblue and other immutable distriutions as a result.

I was on Fedora Workstation so this didn't hit me that time.

I'll review your pr as soon as possible.
