### ISSUE TITLE
App fleet does not detect applications installed via Flatpack

### ISSUE THREAD

**Issue by wada3n** [omegaui/app_fleet#22]
Hi,

I really like this app and I think it has a great idea. It works flawlessly and I haven't had any problems with it.

However, I noticed a bug on my device. App fleet  is unable to find applications installed via flatpak. 
I have 140 applications installed via flatpak and none of them showed up in the app.

> Fedora Linux 39
> GNOME 45.4 

Thank you for your time and consideration.

**Comment by omegaui** [comment]
Hi @wada3n 
Sorry for the delayed reply.

App Fleet already has Flatpak Apps detector.

https://github.com/omegaui/app_fleet/blob/116d6bc068d098c5401e723b4ff8abf3eb0af630/lib/config/assets/generators/linux_app_finder.dart#L51-L52

Maybe it's not the same root location for flatpak storage on your device.
also, I do not know much of Flatpak's storage management.

The default search path set in App Fleet is `'/var/lib/flatpak/exports/share/applications'`
But, if you can provide me the path where all your flatpaks are stored, I'll surely add them and do a release for you.

**Comment by wada3n** [comment]
Hi @omegaui ,

Thanks for your reply.

I have checked the path you mentioned (`/var/lib/flatpak/exports/share/applications`) and it is the same path that I have on my devices. I have also tried on two different devices with Fedora 39, but the problem still persists.

I also think it would be helpful if App Fleet could display a log of the output when it is scanning for applications. This would allow us to track the progress of the scan and identify any errors that may occur.
Best regards,

**Comment by omegaui** [comment]
@wada3n 

>  it would be helpful if App Fleet could display a log of the output when it is scanning for applications.

it does,

in your terminal run the following ...

```shell
app-fleet --debug
```

It's log shows if there are any flatpak applications.

**Comment by wada3n** [comment]
These are the outputs:

> (app-fleet:10379): Gdk-CRITICAL **: 17:01:24.492: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
> ⚡ >> Manager Mode
> ⚡ Injector: Putting RouteService ...
> ⚡ Injector: Putting LinuxAppFinder ...
> ⚡ Injector: Putting AppSession ...
> ⚡ Injector: Putting AppUpdater ...
> ⚡ Injector: Putting AppConfiguration ...
> ⚡ Injector: Putting WorkspaceLauncher ...
> ⚡ Injector: Putting SettingsRepository ...
> ⚡ Injector: Putting HomeRepository ...
> ⚡ Injector: Putting ConfigRepository ...
> ⚡ Injector: Putting LauncherRepository ...
> ⚡ Injector: Putting UpdateRepository ...
> ⚡ AppTheme: Light Mode applied ...
> ⚡ LinuxAppFinder: Caching Icon Paths ...
> ⚡ LinuxAppFinder: Your Icon Theme is Adwaita
> ⚡ LinuxAppFinder: Loading Apps ...
> ⚡ LinuxAppFinder: Unable to find any global snap applications ...
> ⚡ LinuxAppFinder: Loading Apps ... Done!
> ⚡ LinuxAppFinder: I have access to 483 icon files on this system.
> 
> 

app-fleet only shows that there are 111 installed app, none of them is flatpak
> 
![image](https://github.com/omegaui/app_fleet/assets/13304792/e565e7fb-2645-4494-ab17-791400cd4d24)

**Comment by omegaui** [comment]
@wada3n 
Can you please run `ls` in `/var/lib/flatpak/exports/share/applications` and check if it contains `.desktop` entries.
App Fleet is designed to reject those apps whose desktop entry has the `EXEC` property missing.

**Comment by omegaui** [comment]
if possible please provide me the content of at least 3 desktop entries.
I do not use flatpaks, so this may be a reason that App Fleet wasn't tested much for it.

**Comment by wada3n** [comment]
Hi @omegaui ,
Well, here's the content of three of them,

**1- app.drey.Dialect.desktop**

> [Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
StartupNotify=true
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=dialect app.drey.Dialect
Name=Dialect
Comment=Translate between languages
Categories=Network;GTK;
Icon=app.drey.Dialect
Keywords=translate;translation;
X-Purism-FormFactor=Workstation;Mobile;
X-Flatpak=app.drey.Dialect

**2- com.github.tenderowl.frog.desktop**

> [Desktop Entry]
Name[ar]=فروج
Name[cs]=Frog
Name[de]=Frog
Name[es]=Frog
Name[fi]=Frog
Name[fr]=Frog
Name[it]=Frog
Name[ja]=Frog
Name[nl]=Frog
Name[oc]=Frog
Name[ru]=Frog
Name[sv]=Frog
Name[tr]=Kurbağa
Name[uk]=Frog
Name[zh_Hans]=Frog
Name[hi]=Frog
Name=Frog
GenericName[ar]=أداة لاستخراج النصوص
GenericName[cs]=Nástroj pro extrakci textu
GenericName[de]=Textextrahierungswerkzeug
GenericName[es]=Herramienta de extracción de texto
GenericName[fi]=Tekstin purkutyökalu
GenericName[fr]=Outil d’extraction de texte
GenericName[it]=Strumento di estrazione del testo
GenericName[ja]=画面上の文字を検出
GenericName[ko_KR]=텍스트 추출 도구
GenericName[nl]=Tekst­extractie­gereedschap
GenericName[oc]=Aisina d’extraccion de tèxte
GenericName[ru]=Инструмент для извлечения текста
GenericName[tr]=Metin ayıklama aracı
GenericName[uk]=Інструмент отримування тексту
GenericName[zh_Hans]=文本提取工具
GenericName[hi]=टेक्स्ट निष्कर्षण उपकरण
GenericName=Text extraction tool
Comment[ar]=استخراج النصوص من أي صورة أو مقطع فيديو أو موقع
Comment[cs]=Extrahujte text z libovolného obrázku, videa nebo webové stránky
Comment[de]=Text aus jedem Bild, Video oder Webseite extrahieren
Comment[es]=Extraer texto de cualquier imagen, vídeo o página web
Comment[fi]=Pura tekstiä kuvista, videolta tai verkkosivuilta
Comment[fr]=Extrayez du texte de n’importe quelle image, vidéo ou page web
Comment[it]=Estrai il testo da qualsiasi immagine, video o pagina web
Comment[ko_KR]=이미지, 비디오, 웹 페이지에서 텍스트 추출
Comment[nl]=Extraheer tekst vanuit elke afbeelding, video of webpagina
Comment[oc]=Traire lo tèxt de quin imatge, vidèo o pagina web que siá
Comment[ru]=Извлекайте текст из любых изображений, видео или веб-страниц
Comment[tr]=Herhangi bir görüntü, video veya web sayfasından metin ayıkla
Comment[uk]=Отримайте текст з будь-якого зображення, відео чи веб-сторінки
Comment[zh_Hans]=从任何图像、视频、网页中提取文本
Comment[hi]=किसी भी छवि, वीडियो या वेब पेज से टेक्स्ट निकालें
Comment=Extract text from any image, video or web page
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=frog com.github.tenderowl.frog
Icon=com.github.tenderowl.frog
Terminal=false
Type=Application
Categories=GTK;Utility;Office;
StartupNotify=true
Keywords[cs]=OCR;Text;Extrakce;
Keywords[de]=OCR;Text;Extraktion;
Keywords[es]=OCR;Text;Extraction;Texto;Extracción;
Keywords[fi]=OCR;Text;Extraction;teksti;purkaminen;tekstintunnistus;
Keywords[fr]=OCR;Texte;Extraction;extraire;image;QR code;
Keywords[it]=OCR; Testo; Estrazione;
Keywords[ko_KR]=OCR;텍스트;추출;
Keywords[nl]=OCR;Text;Extraction;Tekst;Extractie;QR;
Keywords[oc]=OCR;Tèxte;Extraccion;
Keywords[ru]=OCR;Текст;Извлечение;
Keywords[tr]=OCR;Metin;Ayıkla;
Keywords[uk]=OCR;Text;Extraction;текст;отримування;
Keywords[zh_Hans]=OCR;文本;提取;
Keywords[hi]=OCR;टेक्स्ट;निष्कर्षण;
Keywords=OCR;Text;Extraction;
Actions=extractToClipboard;
X-Purism-FormFactor=Workstation;Mobile;
X-Flatpak=com.github.tenderowl.frog
[Desktop Action extractToClipboard]
Name[cs]=Extrahování textu do schránky
Name[de]=Text in Zwischenablage extrahieren
Name[es]=Extraer texto al portapapeles
Name[fi]=Pura teksti leikepöydälle
Name[fr]=Extraire directement vers le presse-papiers
Name[it]=Estrai il testo negli Appunti
Name[ko_KR]=텍스트를 클립보드로 추출
Name[nl]=Tekst naar het klembord extraheren
Name[oc]=Extraire lo tèxte del quichapapièrs
Name[ru]=Извлечь и скопировать в буфер обмена
Name[tr]=Metni Panoya Çıkar
Name[uk]=Отримати і скопіювати у буфер обміну
Name[zh_Hans]=将文本提取至剪贴板
Name[hi]=टेक्स्ट को क्लिपबोर्ड पर निकालें
Name=Extract Text to the Clipboard
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=frog com.github.tenderowl.frog --extract_to_clipboard

**3- io.bassi.Amberol.desktop**

> [Desktop Entry]
Name[be]=Amberol
Name[ca]=Amberol
Name[cs]=Amberol
Name[da]=Amberol
Name[de]=Amberol
Name[el]=Amberol
Name[en_GB]=Amberol
Name[es]=Amberol
Name[eu]=Amberol
Name[fa]=امبرول
Name[fi]=Amberol
Name[fr]=Amberol
Name[fur]=Amberol
Name[gl]=Amberol
Name[he]=אמברול
Name[hr]=Amberol
Name[hu]=Amberol
Name[id]=Amberol
Name[is]=Amberol
Name[it]=Amberol
Name[ka]=Amberol
Name[ko]=앰버롤
Name[lt]=Amberol
Name[nl]=Amberol
Name[oc]=Amberol
Name[pl]=Amberol
Name[pt]=Amberol
Name[pt_BR]=Amberol
Name[ru]=Amberol
Name[sl]=Amberol
Name[sr]=Амберол
Name[sv]=Amberol
Name[tr]=Amberol
Name[uk]=Амберол
Name[zh_CN]=Amberol
Name=Amberol
GenericName[be]=Музычны прайгравальнік
GenericName[ca]=Reproductor de música
GenericName[cs]=Přehrávač hudby
GenericName[da]=Musikafspiller
GenericName[de]=Musikwiedergabe
GenericName[el]=Αναπαραγωγή μουσικής
GenericName[en_GB]=Music Player
GenericName[es]=Reproductor de música
GenericName[eu]=Musika-erreproduzigailua
GenericName[fa]=پخش‌کنندهٔ آهنگ
GenericName[fi]=Musiikkisoitin
GenericName[fr]=Lecteur de musique
GenericName[fur]=Riprodutôr musicâl
GenericName[gl]=Reprodutor de música
GenericName[he]=נגן מוזיקה
GenericName[hr]=Glazbeni reproduktor
GenericName[hu]=Zenelejátszó
GenericName[id]=Pemutar Musik
GenericName[is]=Tónlistarspilari
GenericName[it]=Lettore musicale
GenericName[ka]=მედია დამკვრელი
GenericName[ko]=음악 재생기
GenericName[lt]=Muzikos grotuvas
GenericName[ne]=सङ्गीत बजाउने
GenericName[nl]=Muziekspeler
GenericName[oc]=Lector de musica
GenericName[pl]=Odtwarzacz muzyki
GenericName[pt]=Reprodutor de música
GenericName[pt_BR]=Reprodutor de músicas
GenericName[ru]=Музыкальный проигрыватель
GenericName[sl]=Predvajalnik glasbe
GenericName[sr]=Програм за пуштање музике
GenericName[sv]=Musikspelare
GenericName[tr]=Müzik Çalar
GenericName[uk]=Програвач музики
GenericName[zh_CN]=音乐播放器
GenericName=Music Player
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=amberol --file-forwarding io.bassi.Amberol @@u %U @@
Icon=io.bassi.Amberol
Terminal=false
Type=Application
Categories=GNOME;GTK;Music;Audio;AudioVideo;
Keywords[be]=player;музычны;прайгравальнік;мультымедыя;аўдыя;прайграванне;плэер;
Keywords[cs]=hudba;přehrávač;média;audio;playlist;
Keywords[da]=musik;afspiller;medie;lyd;afspilningsliste;playliste;
Keywords[de]=music;player;media;audio;playlist;Musik;Wiedergabe;Medien;Audio;Wiedergabeliste;
Keywords[en_GB]=music;player;media;audio;playlist;
Keywords[es]=música;sonido;reproductor;medio;lista;reproducción;
Keywords[eu]=musika;erreproduzigailua;multimedia;audioa;erreprodukzio-zerrenda
Keywords[fa]=music;player:media;موزیک;آهنگ;موسیقی;صدا;صوت;آوا;پخش‌کننده;رسانه;
Keywords[fi]=music;player;media;audio;playlist;musiikki;ääni;soitin;soittolista;
Keywords[fr]=musique;son;lecteur;média;audio;liste de lecture;
Keywords[fur]=musiche;riprodutôr;multimedia;audio;liste di riproduzion;
Keywords[gl]=música;reprodutor;media;son;lista de reprodución;
Keywords[he]=מוזיקה;מוסיקה;שמע;צליל;נגן;מדיה;אודיו;רשימת השמעה;רשימות השמעה;פליליסט;
Keywords[hr]=glazba;reproduktor;medij;zvuk;popis izvođenja;
Keywords[hu]=zene;lejátszó;média;hang;lejátszási lista;
Keywords[id]=musik;pemutar;media;audio;daftar putar;
Keywords[is]=tónlist;spilari;margmiðlun;hljóð;spilun;spilunarlisti
Keywords[it]=musica;lettore;media;audio;playlist;
Keywords[ka]=music;sound;player;media;audio;playlist;
Keywords[ko]=music;음악;곡;player;재생;재생기;media;매체;미디어;audio;오디오;소리;음성;playlist;재생목록;목록;
Keywords[lt]=muzika;grotuvas;medija;garsas;grojaraštis;
Keywords[nl]=muziek;music;speler;player;media;audio;afspeellijst;playlist;
Keywords[oc]=musica;lector;mèdia;audio;àudio;lista de lectura;
Keywords[pl]=muzyka;music;odtwarzacz;player;plejer;media;multimedia;audio;lista odtwarzania;playlista;plejlista;MP3;empetrzy;empetrójka;
Keywords[pt]=música;músicas;music;som;reprodutor;leitor;player;multimédia;áudio;audio;lista de reprodução;playlist;
Keywords[pt_BR]=música;músicas;music;som;reprodutor;player;mídia;áudio;audio;lista de reprodução;playlist;
Keywords[ru]=music;player;media;audio;playlist;музыка;проигрыватель;медиа;аудио;список воспроизведения;
Keywords[sl]=music;player;media;audio;playlist;glasba;predvajalnik;predstavna vsebina;seznam predvajanja;skladbe;pesmi;
Keywords[sr]=музика;пуштач;медија;аудио;списак;music;player;media;audio;playlist;
Keywords[sv]=musik;spelare;media;audio;spellista;
Keywords[tr]=müzik;oynatıcı;çalıcı;çalar;müzik çalar;müzik oynatıcı;medya;ortam;ses;oynatma listesi;çalma listesi;
Keywords[uk]=music;player;media;audio;playlist;музика;звук;програвач;мультимедіа;звук;список відтворення;відтворення;
Keywords[zh_CN]=music;player;media;audio;playlist;音乐;播放器;媒体;音频;播放列表;
Keywords=music;player;media;audio;playlist;
StartupNotify=true
X-SingleMainWindow=true
X-Purism-FormFactor=Workstation;Mobile;
DBusActivatable=true
MimeType=audio/mpeg;audio/wav;audio/x-aac;audio/x-aiff;audio/x-ape;audio/x-flac;audio/x-m4a;audio/x-m4b;audio/x-mp1;audio/x-mp2;audio/x-mp3;audio/x-mpg;audio/x-mpeg;audio/x-mpegurl;audio/x-opus+ogg;audio/x-pn-aiff;audio/x-pn-au;audio/x-pn-wav;audio/x-speex;audio/x-vorbis;audio/x-vorbis+ogg;audio/x-wavpack;inode/directory;
X-Flatpak=io.bassi.Amberol

**Comment by omegaui** [comment]
@wada3n 
Everything seems fine in code at least,
I'm installing flatpak support to fix this issue,
you'll get an update soon.
