### ISSUE TITLE
Most applications don't show up in App Picker

### ISSUE THREAD

**Issue by nathanbibb** [omegaui/app_fleet#25]
I recently had this issue and Uninstalled and Reinstalled the latest version of app-fleet.  The issue persists.

When I try to create a new Workspace Configuration, and select the "Pick an app from your system (Ctrl + F)" button, I only see 6 applications.  These all have ".desktop" files in ~/.local/share/applications.

When starting up using "app-fleet --debug", I get the following output:
(app-fleet:6297): Gdk-CRITICAL **: 13:59:20.577: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
⚡ >> Manager Mode
⚡ Injector: Putting RouteService ...
⚡ Injector: Putting LinuxAppFinder ...
⚡ Injector: Putting AppSession ...
⚡ Injector: Putting AppUpdater ...
⚡ Injector: Putting AppConfiguration ...
⚡ Injector: Putting WorkspaceLauncher ...
⚡ Injector: Putting SettingsRepository ...
⚡ Injector: Putting HomeRepository ...
⚡ Injector: Putting ConfigRepository ...
⚡ Injector: Putting LauncherRepository ...
⚡ Injector: Putting UpdateRepository ...
⚡ AppTheme: Light Mode applied ...
⚡ LinuxAppFinder: Caching Icon Paths ...
🚨 ERROR No Primary Icons Directory found
🚨 ERROR No Primary Icons Directory found
⚡ LinuxAppFinder: Your Icon Theme is Pop
⚡ LinuxAppFinder: Loading Apps ...
⚡ LinuxAppFinder: Unable to find any global snap applications ...
⚡ LinuxAppFinder: Unable to find any global flatpak applications ...
⚡ LinuxAppFinder: Loading Apps ... Done!
⚡ LinuxAppFinder: I have access to 10 icon files on this system.

I am running pop-os 22.04, uname -a is the following:
Linux pop-os 6.9.3-76060903-generic #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S x86_64 x86_64 x86_64 GNU/Linux

**Comment by nathanbibb** [comment]
Another note - I am not seeing this behavior in v1.0.1+1 and earlier.

**Comment by omegaui** [comment]
Hi there! @nathanbibb

Sorry for the late reply, didn't got any notifications from GitHub.

> (app-fleet:6297): Gdk-CRITICAL **: 13:59:20.577: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
The above is not an issue, it's a bug in the flutter desktop framework for gtk. So, we can just ignore it right now.

However, the thing to consider is this part of the log:
> ⚡ LinuxAppFinder: Unable to find any global snap applications ...
⚡ LinuxAppFinder: Unable to find any global flatpak applications ...

Do you have any snaps or flatpaks installed, can you check in these locations if they have any .desktop file?
```
/var/lib/snapd/desktop/applications
/var/lib/flatpak/exports/share/applications
/usr/local/share/applications
~/.local/share/flatpak
```

also, I'm on Ubuntu 24.10, Your Pop OS is based on ubuntu 22.04, saying, that we both have same parent distro, but still if your os has different locations for snap or flatpaks installations, then, please share the locations here, I'll add it to a new version v1.0.2+2 and do a quick release, so that you get the latest of App Fleet.

**Comment by omegaui** [comment]
Here's a part of app-fleet that searches app on any distro

https://github.com/omegaui/app_fleet/blob/20d7443ce44a6219824856ee893dfff326b04750/lib/config/assets/generators/linux_app_finder.dart#L30-L34

you can also try experimenting by changing the `'/usr/local/share/applications'` value to a path where you have most of your apps installed.

**Comment by nathanbibb** [comment]
Thanks for the reply, @omegaui !

My flatpak desktop files are located here:
`~/.local/share/flatpak/exports/share/applications`

The majority of my application desktop files are located here"
`/usr/share/applications/`

Not sure if that's different than your Ubuntu 24.04 system, but I'm pretty sure that's POSIX standard.  And as I said above, this location is searched for versions v1.0.1+1 and earlier.

Thanks!

**Comment by nathanbibb** [comment]
I tried updating the source as you suggested, but when I used the `app-fleet/packages/install-from-source.sh` command, the app would not launch - there was nothing in `~/.config/app-fleet` apparently.  This happened regardeless of whether I made any changes to the dart file.

Priority on this can be low, for me at least - I got app-fleet working by manually entering in application paths.  So I'm good at the moment, but you should be looking for desktop files in `/usr/share/applications`, and it appears you are not, at least  on my system.

Also, thanks for creating a wonderful app manager!  I love app-fleet, and I use it everyday!

**Comment by omegaui** [comment]
@nathanbibb Thank you for your contribution in pointing this issue out.
I've releases v1.0.3+1 with changes to fix your issue, and now you can get the latest of App Fleet.
Your existing release will automatically notify you about the update if you have enabled auto updates in the app settings.

**Comment by omegaui** [comment]
> I tried updating the source as you suggested, but when I used the app-fleet/packages/install-from-source.sh command, the app would not launch - there was nothing in ~/.config/app-fleet apparently

I've added a notice in `package/build-bundle.sh` file, if you wish to build from source.
